#!/usr/bin/with-contenv bash

# Comprobamos si existe instalador de y lanzamos comprobador de version
if [ ! -e /app/scripts/checknormandyver.sh ]; then
	(mkdir -p /app/scripts/ && wget -P /app/scripts/ https://raw.githubusercontent.com/monkey-brothers/monkeytv/master/scripts/checknormandyver.sh && cd /app/scripts && sh checknormandyver.sh)
else
  (cd /app/scripts && sh checknormandyver.sh)
fi
# Comprobamos si estan los archivos de configuracion de Oscam
[[ ! -e /config/oscam/oscam.user ]] && \
        (cp /app/monkeyfiles/oscam.* /config/oscam/)
# Comprobamos si existe el archivo de configuracion de enlace entre TVH y Oscam
[[ ! -e /config/caclient/0c84089713e3668e1cbba92f486b68c0 ]] && \
        (mkdir -p /config/caclient/ && cp /app/monkeyfiles/0c84089713e3668e1cbba92f486b68c0 /config/caclient/)
